# Generated by Django 4.1.5 on 2023-04-06 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0018_checkout_payment_type_alter_checkout_checkout_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='checkout_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 6, 15, 56, 3, 26624, tzinfo=datetime.timezone.utc)),
        ),
    ]
